services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  php:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - '.:/var/www/task-mgr'
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    volumes:
      - '.:/var/www/task-mgr'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '8080:80'
    depends_on:
      - php
      - database

volumes:
  database_data:
###< doctrine/doctrine-bundle ###
